"""Update author

Revision ID: 4476a771ee5e
Revises: 4bd7d957697a
Create Date: 2024-06-22 19:35:55.022555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4476a771ee5e'
down_revision = '4bd7d957697a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.drop_column('auther')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auther', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
