"""empty message

Revision ID: 4dd0d75d2adf
Revises: 4476a771ee5e
Create Date: 2024-06-23 19:02:33.964200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dd0d75d2adf'
down_revision = '4476a771ee5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
